[package]
name = "lambda_core"
version = "0.2.26"
authors = ["Samuel Wilder <pebazium@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
colored = "1.7"
flame = "0.2.2"
clap = "2.33.0"
