version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    branches:
      only:
        - master
    steps:
      #- setup_remote_docker
      - checkout
      - run: rustup target add x86_64-pc-windows-gnu
      - run: cargo build --target x86_64-pc-windows-gnu --release -- -C linker=x86_64-w64-mingw32-gcc
      #- run: cargo install cross
      #- run: cross build --target aarch64-unknown-linux-gnu
      - run: ls target



# docker:
#   - image: docker
# branches:
#   only:
#     - master
# steps:
#   - run: curl https://sh.rustup.rs -sSf | sh
#   - run: cargo install cross
#   - checkout


# I could docker run <rust-container> --cross build --target <target>

#   - run: echo "Building..."
#   - run: cargo build --release
#   - run: ls target/release/
#   - run: target/release/lambda_core -c '(print "Hello World!")'
#   - run: cargo test --release
#   - run: echo "Done"


# https://circleci.com/blog/exploring-domain-driven-design-at-circleci/
# Publish only on tag
#   publish:
#     docker:
#       - image: circleci/golang
#     branches:
#       only:
#         - master


# workflows:
#   version: 2
#   main:
#     jobs:
#       - build:
#           filters:
#             tags:
#               only: /^v\d+\.\d+\.\d+$/
#       - publish:
#           requires:
#             - build
#           filters:
#             branches:
#               ignore: /.*/
#             tags:
#               only: /^v\d+\.\d+\.\d+$/
