version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: sudo apt-get install -y mingw-w64
      - run: rustup target add x86_64-pc-windows-gnu
      # https://github.com/rust-lang/rust/issues/33465
      - run: cargo rustc --release --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc
      - run: ls target
      - run:
          name: Parse LambdaCore version
          #command: cat Cargo.toml | head -n 3 | tail -n 1 | cut -c 12- | cut -c -5 > target/VERSION
          command: cat Cargo.toml | head -n 3 | tail -n 1 | cut -c 12- | rev | cut -c 2- | rev > target/VERSION
      - persist_to_workspace:
          root: target
          paths:
            - ./*

  # https://circleci.com/blog/exploring-domain-driven-design-at-circleci/
  # Publish only on tag
  publish:
    docker:
      - image: cibuilds/github:0.10
    environment:
      FOO: bar
      
    steps:
      - attach_workspace:
          at: target
      - run: ls target
      - run: ls target/x86_64-pc-windows-gnu
      - run: ls target/x86_64-pc-windows-gnu/release
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=v$(cat target/VERSION)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} target/x86_64-pc-windows-gnu/release/lambda_core.exe


# Perhaps I should just deploy every time someone
# pushes to master. It would be easier than this
# tag nonesense.
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
