version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: echo "Building..."
      - run: cargo build --release
      - run: ls target/release/
      - run: echo "Done"

